FROM ubuntu:18.04

RUN apt update && apt install openssh-server sudo git -y

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 raka 

RUN  echo 'raka:raka' | chpasswd

# Install NodeJS requirements
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && \
    apt-get install nodejs npm curl -y && npm install --global yarn

RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]