#!/bin/bash


repository=$1
framework=$2
directory=$3
prebuild=$4
postbuild=$5


printf "<GroupedLog>\n"
printf "Initial setups (...)\n"

echo " _        __       "
echo "(_)_ __  / _| ___  "
echo "| | '_ \\| |_ / _ \\ "
echo "| | | | |  _| (_) |"
echo "|_|_| |_|_|  \\___/ "
echo "                   "
echo "=========================================================================="
echo "Common Module       : Global Config"
echo "Repository          : github.com/creativetimofficial/nextjs-material-kit"
echo "Creator             : prakasa@devetek.com"
echo "Full Source Dir     : ."
echo "=========================================================================="
echo ""
printf "</GroupedLog>\n"


# Title       : Git Command
# Author      : Nedya Prakasa
# Date        : 02 Dec 2021
# Description : Git command to handle folder and head condition
# Example repo failed build https://github.com/jovimoura/ecommerce-next.git
printf "\n<GroupedLog>\n"
printf "Initial setups folder and git head from framework $framework (...)\n"
if [ ! -d $directory ]; then
    git clone $repository
fi

cd $directory
printf "</GroupedLog>\n"


# Title       : Install All Local Deps
# Author      : Nedya Prakasa
# Date        : 02 Dec 2021
# Description : Install all require local dependencies
printf "\n<GroupedLog>\n"
printf "Install local dependencies\n"
$prebuild
printf "</GroupedLog>\n"

# Title       : Install Service
# Author      : Nedya Prakasa
# Date        : 02 Dec 2021
# Description : Install services can execute multiple command, such us (cp config.example .env && yarn build)
printf "\n<GroupedLog>\n"
printf "Install services\n"
$postbuild
printf "</GroupedLog>\n"

# Require String To Exit From Remote Access
printf "\n[BASH-SUCCESS] - KRATOS-FINISHED\n"